export interface Avatar {
  id: number;
  imgSrc: any;
}

export const avatarList: Avatar[] = [
  { id: 1, imgSrc: require('../assets/avatars/avatar-1.png') },
  { id: 2, imgSrc: require('../assets/avatars/avatar-2.png') },
  { id: 3, imgSrc: require('../assets/avatars/avatar-3.png') },
  { id: 4, imgSrc: require('../assets/avatars/avatar-4.png') },
  { id: 5, imgSrc: require('../assets/avatars/avatar-5.png') },
  { id: 6, imgSrc: require('../assets/avatars/avatar-6.png') },
  { id: 7, imgSrc: require('../assets/avatars/avatar-7.png') },
  { id: 8, imgSrc: require('../assets/avatars/avatar-8.png') },
  { id: 9, imgSrc: require('../assets/avatars/avatar-9.png') },
  { id: 10, imgSrc: require('../assets/avatars/avatar-10.png') },
  { id: 11, imgSrc: require('../assets/avatars/avatar-11.png') },
  { id: 12, imgSrc: require('../assets/avatars/avatar-12.png') },
  { id: 13, imgSrc: require('../assets/avatars/avatar-13.png') },
  { id: 14, imgSrc: require('../assets/avatars/avatar-14.png') },
  { id: 15, imgSrc: require('../assets/avatars/avatar-15.png') },
  { id: 16, imgSrc: require('../assets/avatars/avatar-16.png') },
  { id: 17, imgSrc: require('../assets/avatars/avatar-17.png') },
  { id: 18, imgSrc: require('../assets/avatars/avatar-18.png') },
  { id: 19, imgSrc: require('../assets/avatars/avatar-19.png') },
  { id: 20, imgSrc: require('../assets/avatars/avatar-20.png') },
  { id: 21, imgSrc: require('../assets/avatars/avatar-21.png') },
  { id: 22, imgSrc: require('../assets/avatars/avatar-22.png') },
  { id: 23, imgSrc: require('../assets/avatars/avatar-23.png') },
  { id: 24, imgSrc: require('../assets/avatars/avatar-24.png') },
  { id: 25, imgSrc: require('../assets/avatars/avatar-25.png') },
  { id: 26, imgSrc: require('../assets/avatars/avatar-26.png') },
  { id: 27, imgSrc: require('../assets/avatars/avatar-27.png') },
  { id: 28, imgSrc: require('../assets/avatars/avatar-28.png') },
  { id: 29, imgSrc: require('../assets/avatars/avatar-29.png') },
  { id: 30, imgSrc: require('../assets/avatars/avatar-30.png') },
  { id: 31, imgSrc: require('../assets/avatars/avatar-31.png') },
  { id: 32, imgSrc: require('../assets/avatars/avatar-32.png') },
  { id: 33, imgSrc: require('../assets/avatars/avatar-33.png') },
  { id: 34, imgSrc: require('../assets/avatars/avatar-34.png') },
  { id: 35, imgSrc: require('../assets/avatars/avatar-35.png') },
  { id: 36, imgSrc: require('../assets/avatars/avatar-36.png') },
  { id: 37, imgSrc: require('../assets/avatars/avatar-37.png') },
  { id: 38, imgSrc: require('../assets/avatars/avatar-38.png') },
  { id: 39, imgSrc: require('../assets/avatars/avatar-39.png') },
  { id: 40, imgSrc: require('../assets/avatars/avatar-40.png') },
  { id: 41, imgSrc: require('../assets/avatars/avatar-41.png') },
  { id: 42, imgSrc: require('../assets/avatars/avatar-42.png') },
  { id: 43, imgSrc: require('../assets/avatars/avatar-43.png') },
  { id: 44, imgSrc: require('../assets/avatars/avatar-44.png') },
  { id: 45, imgSrc: require('../assets/avatars/avatar-45.png') },
  { id: 46, imgSrc: require('../assets/avatars/avatar-46.png') },
  { id: 47, imgSrc: require('../assets/avatars/avatar-47.png') },
];


